name: windows-x86_64

on: [ push, pull_request ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  windows:
    if: 1
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all

      - uses: actions/checkout@v3
      - name: Prepare Chromium Run Environment
        run: |
          ipconfig /all

      - name: Download Chromium
        shell: bash
        run: |
          set -x
          bash tools/download-chromium.sh

      - name: Download Firefox
        shell: bash
        run: |
          set -x
          bash tools/download-firefox-latest.sh
          
      - name: Test
        shell: cmd
        run: |
          @chcp 65001>nul
          echo foo=bar >> %GITHUB_OUTPUT%
